### ISSUE TITLE
Couldn't open audio device. Any support for remote servers without audio devices?

### ISSUE THREAD

**Issue by Litchiware** [chflame163/ComfyUI_MSSpeech_TTS#2]
pygame 2.5.2 (SDL 2.28.2, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI/custom_nodes/ComfyUI_MSSpeech_TTS/__init__.py", line 18, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ComfyUI/custom_nodes/ComfyUI_MSSpeech_TTS/py/playsoundloop.py", line 6, in <module>
    mixer.init()
pygame.error: ALSA: Couldn't open audio device: No such file or directory

Cannot import ComfyUI/custom_nodes/ComfyUI_MSSpeech_TTS module for custom nodes: ALSA: Couldn't open audio device: No such file or directory

**Comment by GentlemanHu** [comment]
+1

```python
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/nodes.py", line 1818, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_MSSpeech_TTS/__init__.py", line 18, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_MSSpeech_TTS/py/playsoundloop.py", line 6, in <module>
    mixer.init()
pygame.error: ALSA: Couldn't open audio device: No such file or directory

```

**Comment by chflame163** [comment]
[https://github.com/pygame/pygame/issues/3923](https://github.com/pygame/pygame/issues/3923) If this can be helpful to you
